### PR TITLE
Composer initial support

### PR DESCRIPTION
**Pull request by philwareham**

### CODE REVIEW

**Comment by philwareham** [comment]
Cheers Stef! Can you please register this repo on packagist.org and then we can test Composer installation works.

**Comment by Bloke** [comment]
Do we wanna rename it first?

**Comment by philwareham** [comment]
Yes please! smd_contact (or somethingelse_contact) seemed to be the general consensus. Also the classes such as zemerror probably need renaming.

**Comment by philwareham** [comment]
Hi @bloke can we get the rename of this done this week if possible? I’d like the Textpattern site to launch with all its plugins installed via Composer (and this is the only plugin that doesn’t). Maybe you can keep the ‘zem_’ name as an alias so that tags can be backwards compatible?

**Pull request merged**
